name: declarate
description: >
  Declarate is a lightweight, stateless, and declarative state management library 
  for Flutter. It enables reactive UI updates without State or Bloc, inspired by 
  SwiftUI and declarative architectures. Includes Declarate (logic holder), 
  Declarion (multi-provider), and Declarator (builder).

version: 0.0.1
homepage: https://github.com/updown-interactive/declarate
repository: https://github.com/updown-interactive/declarate
issue_tracker: https://github.com/updown-interactive/declarate/issues
documentation: https://github.com/updown-interactive/declarate#readme
license: MIT

environment:
  sdk: ^3.5.0
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.24.0

flutter:
  uses-material-design: false
